### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by benhaim** [OrelAlon/foodbook-app#9]
why is the favicon 8.8MB!? 
I would have downloaded it to see what it is but I guess its a virus lol

**Comment by OrelAlon** [comment]
also known as a shortcut icon, website icon, tab icon, URL icon, or bookmark icon 
In this project, a picture of a hamburger :)

**Comment by OrelAlon** [comment]
also known as a shortcut icon, website icon, tab icon, URL icon, or bookmark icon
In this project, a picture of a hamburger :)
